#/bin/sh

#script to GenerateData.py
pyspark --packages com.databricks:spark-csv_2.10:1.4.0 GenerateData.py /hadoop/hdfs/INPUTPARQUET/contr/DepositHistory_parquet /hadoop/hdfs/INPUTPARQUET/dbo/SubselectionOfClients_parquet /hadoop/hdfs/demobank/INPUTPARQUET/contr/DepositHistory_parquet /hadoop/hdfs/demobank/INPUTCSV/contr/DepositHistory.csv
pyspark --packages com.databricks:spark-csv_2.10:1.4.0 GenerateData.py /hadoop/hdfs/INPUTPARQUET/contr/AccountProperties_parquet /hadoop/hdfs/INPUTPARQUET/dbo/SubselectionOfClients_parquet /hadoop/hdfs/demobank/INPUTPARQUET/contr/AccountProperties_parquet /hadoop/hdfs/demobank/INPUTCSV/contr/AccountProperties.csv
pyspark --packages com.databricks:spark-csv_2.10:1.4.0 GenerateData.py /hadoop/hdfs/INPUTPARQUET/contr/CreditHistory_parquet /hadoop/hdfs/INPUTPARQUET/dbo/SubselectionOfClients_parquet /hadoop/hdfs/demobank/INPUTPARQUET/contr/CreditHistory_parquet /hadoop/hdfs/demobank/INPUTCSV/contr/CreditHistory.csv
pyspark --packages com.databricks:spark-csv_2.10:1.4.0 GenerateData.py /hadoop/hdfs/INPUTPARQUET/cli/Client_parquet /hadoop/hdfs/INPUTPARQUET/dbo/SubselectionOfClients_parquet /hadoop/hdfs/demobank/INPUTPARQUET/cli/Client_parquet /hadoop/hdfs/demobank/INPUTCSV/cli/Client.csv
pyspark --packages com.databricks:spark-csv_2.10:1.4.0 GenerateData.py /hadoop/hdfs/INPUTPARQUET/cli/ClientBlackList_parquet /hadoop/hdfs/INPUTPARQUET/dbo/SubselectionOfClients_parquet /hadoop/hdfs/demobank/INPUTPARQUET/cli/ClientBlackList_parquet /hadoop/hdfs/demobank/INPUTCSV/cli/ClientBlackList.csv
pyspark --packages com.databricks:spark-csv_2.10:1.4.0 GenerateData.py /hadoop/hdfs/INPUTPARQUET/chan/ComplaintLog_parquet /hadoop/hdfs/INPUTPARQUET/dbo/SubselectionOfClients_parquet /hadoop/hdfs/demobank/INPUTPARQUET/chan/ComplaintLog_parquet /hadoop/hdfs/demobank/INPUTCSV/chan/ComplaintLog.csv
pyspark --packages com.databricks:spark-csv_2.10:1.4.0 GenerateData.py /hadoop/hdfs/INPUTPARQUET/crb/CreditBureauRaport_parquet /hadoop/hdfs/INPUTPARQUET/dbo/SubselectionOfClients_parquet /hadoop/hdfs/demobank/INPUTPARQUET/crb/CreditBureauRaport_parquet /hadoop/hdfs/demobank/INPUTCSV/crb/CreditBureauRaport.csv
pyspark --packages com.databricks:spark-csv_2.10:1.4.0 GenerateData.py /hadoop/hdfs/INPUTPARQUET/crb/CreditBureauRequests_parquet /hadoop/hdfs/INPUTPARQUET/dbo/SubselectionOfClients_parquet /hadoop/hdfs/demobank/INPUTPARQUET/crb/CreditBureauRequests_parquet /hadoop/hdfs/demobank/INPUTCSV/crb/CreditBureauRequests.csv
pyspark --packages com.databricks:spark-csv_2.10:1.4.0 GenerateData.py /hadoop/hdfs/INPUTPARQUET/crb/CreditBureau_parquet /hadoop/hdfs/INPUTPARQUET/dbo/SubselectionOfClients_parquet /hadoop/hdfs/demobank/INPUTPARQUET/crb/CreditBureau_parquet /hadoop/hdfs/demobank/INPUTCSV/crb/CreditBureau.csv
pyspark --packages com.databricks:spark-csv_2.10:1.4.0 GenerateData.py /hadoop/hdfs/INPUTPARQUET/chan/BranchVisitLog_parquet /hadoop/hdfs/INPUTPARQUET/dbo/SubselectionOfClients_parquet /hadoop/hdfs/demobank/INPUTPARQUET/chan/BranchVisitLog_parquet /hadoop/hdfs/demobank/INPUTCSV/chan/BranchVisitLog.csv
pyspark --packages com.databricks:spark-csv_2.10:1.4.0 GenerateData.py /hadoop/hdfs/INPUTPARQUET/chan/InternetBankingLog_parquet /hadoop/hdfs/INPUTPARQUET/dbo/SubselectionOfClients_parquet /hadoop/hdfs/demobank/INPUTPARQUET/chan/InternetBankingLog_parquet /hadoop/hdfs/demobank/INPUTCSV/chan/InternetBankingLog.csv
pyspark --packages com.databricks:spark-csv_2.10:1.4.0 GenerateData.py /hadoop/hdfs/INPUTPARQUET/chan/LoggingContract_parquet /hadoop/hdfs/INPUTPARQUET/dbo/SubselectionOfClients_parquet /hadoop/hdfs/demobank/INPUTPARQUET/chan/LoggingContract_parquet /hadoop/hdfs/demobank/INPUTCSV/chan/LoggingContract.csv
pyspark --packages com.databricks:spark-csv_2.10:1.4.0 GenerateData.py /hadoop/hdfs/INPUTPARQUET/chan/TokenUsageLog_parquet /hadoop/hdfs/INPUTPARQUET/dbo/SubselectionOfClients_parquet /hadoop/hdfs/demobank/INPUTPARQUET/chan/TokenUsageLog_parquet /hadoop/hdfs/demobank/INPUTCSV/chan/TokenUsageLog.csv
pyspark --packages com.databricks:spark-csv_2.10:1.4.0 GenerateData.py /hadoop/hdfs/INPUTPARQUET/dict/TypeOfAction_parquet /hadoop/hdfs/INPUTPARQUET/dbo/SubselectionOfClients_parquet /hadoop/hdfs/demobank/INPUTPARQUET/dict/TypeOfAction_parquet /hadoop/hdfs/demobank/INPUTCSV/dict/TypeOfAction.csv
pyspark --packages com.databricks:spark-csv_2.10:1.4.0 GenerateData.py /hadoop/hdfs/INPUTPARQUET/contr/Transactions_parquet /hadoop/hdfs/INPUTPARQUET/dbo/SubselectionOfClients_parquet /hadoop/hdfs/demobank/INPUTPARQUET/contr/Transactions_parquet /hadoop/hdfs/demobank/INPUTCSV/contr/Transactions.csv
pyspark --packages com.databricks:spark-csv_2.10:1.4.0 GenerateData.py /hadoop/hdfs/INPUTPARQUET/chan/InboundCallLog_parquet /hadoop/hdfs/INPUTPARQUET/dbo/SubselectionOfClients_parquet /hadoop/hdfs/demobank/INPUTPARQUET/chan/InboundCallLog_parquet /hadoop/hdfs/demobank/INPUTCSV/chan/InboundCallLog.csv
pyspark --packages com.databricks:spark-csv_2.10:1.4.0 GenerateData.py /hadoop/hdfs/INPUTPARQUET/chan/InboundCallReason_parquet /hadoop/hdfs/INPUTPARQUET/dbo/SubselectionOfClients_parquet /hadoop/hdfs/demobank/INPUTPARQUET/chan/InboundCallReason_parquet /hadoop/hdfs/demobank/INPUTCSV/chan/InboundCallReason.csv
pyspark --packages com.databricks:spark-csv_2.10:1.4.0 GenerateData.py /hadoop/hdfs/INPUTPARQUET/appl/CreditApplication_parquet /hadoop/hdfs/INPUTPARQUET/dbo/SubselectionOfClients_parquet /hadoop/hdfs/demobank/INPUTPARQUET/appl/CreditApplication_parquet /hadoop/hdfs/demobank/INPUTCSV/appl/CreditApplication.csv
pyspark --packages com.databricks:spark-csv_2.10:1.4.0 GenerateData.py /hadoop/hdfs/INPUTPARQUET/appl/RiskCategories_parquet /hadoop/hdfs/INPUTPARQUET/dbo/SubselectionOfClients_parquet /hadoop/hdfs/demobank/INPUTPARQUET/appl/RiskCategories_parquet /hadoop/hdfs/demobank/INPUTCSV/appl/RiskCategories.csv
pyspark --packages com.databricks:spark-csv_2.10:1.4.0 GenerateData.py /hadoop/hdfs/INPUTPARQUET/seg/ClientSegment_parquet /hadoop/hdfs/INPUTPARQUET/dbo/SubselectionOfClients_parquet /hadoop/hdfs/demobank/INPUTPARQUET/seg/ClientSegment_parquet /hadoop/hdfs/demobank/INPUTCSV/seg/ClientSegment.csv
pyspark --packages com.databricks:spark-csv_2.10:1.4.0 GenerateData.py /hadoop/hdfs/INPUTPARQUET/score/ClientScore_parquet /hadoop/hdfs/INPUTPARQUET/dbo/SubselectionOfClients_parquet /hadoop/hdfs/demobank/INPUTPARQUET/score/ClientScore_parquet /hadoop/hdfs/demobank/INPUTCSV/score/ClientScore.csv
pyspark --packages com.databricks:spark-csv_2.10:1.4.0 GenerateData.py /hadoop/hdfs/INPUTPARQUET/contr/AggTransactions_parquet /hadoop/hdfs/INPUTPARQUET/dbo/SubselectionOfClients_parquet /hadoop/hdfs/demobank/INPUTPARQUET/contr/AggTransactions_parquet /hadoop/hdfs/demobank/INPUTCSV/contr/AggTransactions.csv
pyspark --packages com.databricks:spark-csv_2.10:1.4.0 GenerateData.py /hadoop/hdfs/INPUTPARQUET/var/CashLoanForRandomSample_parquet /hadoop/hdfs/INPUTPARQUET/dbo/SubselectionOfClients_parquet /hadoop/hdfs/demobank/INPUTPARQUET/var/CashLoanForRandomSample_parquet /hadoop/hdfs/demobank/INPUTCSV/var/CashLoanForRandomSample.csv
pyspark --packages com.databricks:spark-csv_2.10:1.4.0 GenerateData.py /hadoop/hdfs/INPUTPARQUET/dict/ClientContractDateMapping_parquet /hadoop/hdfs/INPUTPARQUET/dbo/SubselectionOfClients_parquet /hadoop/hdfs/demobank/INPUTPARQUET/dict/ClientContractDateMapping_parquet /hadoop/hdfs/demobank/INPUTCSV/dict/ClientContractDateMapping.csv